export const GRID_COLS = 24;
export const GRID_ROWS = 32;
export const CANVAS_WIDTH = 800;
export const CANVAS_HEIGHT = 960;
export const ARENA_HEIGHT = 768;
export const UI_HEIGHT = 192;
export const CELL_WIDTH = CANVAS_WIDTH / GRID_COLS;       // 33.33
export const CELL_HEIGHT = ARENA_HEIGHT / GRID_ROWS;      // 24
export const MOMENTUM_INFLUENCE_FACTOR = 120;
export const PARRY_WINDOW_MS = 8;
export const PARRY_SLOWDOWN_SCALE = 0.15;
export const PARRY_SLOWDOWN_DURATION_MS = 600;
export const PHASE_TRANSITION_PAUSE_MS = 1500;
export const SHIELD_BREAK_LOCKOUT_MS = 3000;
export const GRID_LINE_ALPHA = 0.08;
export const CELL_HIGHLIGHT_ALPHA = 0.35;
export const WARNING_HIGHLIGHT_ALPHA = 0.2;
export const PLATFORM_ROW = 30;
export const PLATFORM_WIDTH_CELLS = 4;
